### ISSUE TITLE
This color is unfriendly

### ISSUE THREAD

**Issue by cloudyan** [enyancc/vscode-ext-color-highlight#33] opened 2017-08-17 03:59 UTC
This color is unfriendly

![image](https://user-images.githubusercontent.com/912821/29395443-6a06b89e-82d6-11e7-8c56-ccbb8e5910ca.png)

**Comment by ferretwithaberet** [comment] 2021-06-16 17:34
Duplicate of #32.

**Closed by ferretwithaberet** 2021-06-16 17:34 UTC
