### ISSUE TITLE
hex highlight 0xffffff

### ISSUE THREAD

**Issue by djmisterjon** [enyancc/vscode-ext-color-highlight#43] opened 2018-03-05 14:50 UTC
Hi, its possible to add feature for detect code like  **0xffffff** ???

example 
```javascript
     var lineX_ = new PIXI.Graphics();
            console.log('lineX_: ', lineX_);
                lineX_.lineStyle(48, 0xffffff);
                lineX_.moveTo(0,0);
                lineX_.lineTo(1600*2, 0);
                lineX_.pivot.x = lineX_.width/2;
                lineX_.alpha = 0.4;
```

thanks

**Comment by ferretwithaberet** [comment] 2021-06-16 17:37
Duplicate of #30.

**Closed by ferretwithaberet** 2021-06-16 17:37 UTC
