### ISSUE TITLE
Hex colors starting in 0x

### ISSUE THREAD

**Issue by Marcos92** [enyancc/vscode-ext-color-highlight#41] opened 2017-11-29 11:08 UTC
Hello, is it possible to add support to hex color int starting in 0x? (Like 0xFFFFFF, equivalent to #FFFFFF) Thanks in advance!

**Comment by ferretwithaberet** [comment] 2021-06-16 17:35
Duplicate of #30.

**Closed by ferretwithaberet** 2021-06-16 17:35 UTC
